services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      POSTGRES_USER: nld_db_user
      POSTGRES_PASSWORD: nld_db_pass
      POSTGRES_DB: nld_dev_db
    ports:
      - 6543:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - database_volume:/var/lib/postgresql/data

volumes:
  database_volume:
